/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import libraries.formularios.libVentaProductos;
import libraries.identidades.Inventario;

/**
 *
 * @author Ellet
 */
public class AñadirProducto extends javax.swing.JFrame {

    public  javax.swing.JSpinner getContadorproductos() {
        return contadorproductos;
    }

    public  void setContadorproductos(javax.swing.JSpinner aContadorproductos) {
        contadorproductos = aContadorproductos;
    }
    private libVentaProductos lvp = new libVentaProductos();
    private VentaProductos vp;
    public AñadirProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbnombre.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbnombre = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        contadorproductos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        botoncancelar = new javax.swing.JButton();
        botonañadir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("SDMT - VENTA DE PRODUCTOS ");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 21, -1, -1));

        cbnombre.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnombreActionPerformed(evt);
            }
        });
        getContentPane().add(cbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 91, 372, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        contadorproductos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        contadorproductos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        contadorproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contadorproductosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contadorproductosKeyTyped(evt);
            }
        });
        getContentPane().add(contadorproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 132, 62, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 185, 121, 51));

        botonañadir.setText("AÑADIR");
        botonañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonañadirActionPerformed(evt);
            }
        });
        getContentPane().add(botonañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 185, 121, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/papyrus.jpg"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void cbnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnombreActionPerformed
        if(cbnombre.getSelectedIndex() != -1){
           SetMaxValue();
           botonañadir.setEnabled(true);
        }
        else{
            botonañadir.setEnabled(false);
        }
    }//GEN-LAST:event_cbnombreActionPerformed

    private void botonañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonañadirActionPerformed
        if(VerificarEspaciosAñadir()){
            JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONE EL PRODUCTO/CANTIDAD CORRECTO/S", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            vp.setTbventasData((Inventario) cbnombre.getSelectedItem());
            this.setVisible(false);
            setTotales();
            vp.setProductos(lvp.ModificarCantidadEspecifica((Integer)contadorproductos.getValue(),(Inventario) cbnombre.getSelectedItem(), vp.getProductos()));
        }
        
    }//GEN-LAST:event_botonañadirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        
    }//GEN-LAST:event_formWindowDeactivated

    private void contadorproductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadorproductosKeyPressed
        
        
    }//GEN-LAST:event_contadorproductosKeyPressed

    private void contadorproductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadorproductosKeyTyped
        
    }//GEN-LAST:event_contadorproductosKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirProducto().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonañadir;
    private javax.swing.JButton botoncancelar;
    public static javax.swing.JComboBox cbnombre;
    private javax.swing.JSpinner contadorproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public void cargarProductos(){
        List<Inventario> productos= vp.getProductos();
        cbnombre.removeAllItems();
        for(Inventario inventario : productos){
            if(inventario.getCantidad() > 1){
                cbnombre.addItem(inventario);
            }
        }
        cbnombre.setSelectedIndex(-1);
    }

    public void SetMaxValue(){
        SpinnerNumberModel spmodel = (SpinnerNumberModel) contadorproductos.getModel();
        Inventario producto = (Inventario) cbnombre.getSelectedItem();
        spmodel.setMaximum(producto.getCantidad());
        contadorproductos.setModel(spmodel);
    }
    
    //GETTERS Y SETTERS DE LA CLASE
    public VentaProductos getVp() {
        return vp;
    }

    public void setVp(VentaProductos vp) {
        this.vp = vp;
    }
    
    public void setTotales(){
        double subtotal = lvp.CalcularSubtotal(vp.getTbventasDataColumn(5));
        vp.setTxtsubtotal(lvp.ConvertirFormatear(subtotal));
        double iva = lvp.calcularIva(subtotal);
        vp.setTxtiva(lvp.ConvertirFormatear(iva));
        double total = lvp.total(subtotal, iva);
        vp.setTxttotal(lvp.ConvertirFormatear(total));
        
    }
    
    
    public boolean VerificarEspaciosAñadir(){
        boolean espacio = false;
        SpinnerNumberModel spm = (SpinnerNumberModel) contadorproductos.getModel();
        if(cbnombre.getSelectedIndex() == -1){
            espacio = true;
        }
        if(Integer.parseInt(spm.getValue().toString()) > Integer.parseInt(spm.getMaximum().toString())){
            espacio = true; 
        }
        return espacio;
    }


}
