/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;

import javax.swing.JOptionPane;
import libraries.formularios.libAñadirProducto;
import libraries.formularios.libVentaProductos;

/**
 *
 * @author Ellet
 */
public class AñadirProducto extends javax.swing.JFrame {
    
    
    public AñadirProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        new libAñadirProducto().CargarProductos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbnombre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        contadorproductos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        botoncancelar = new javax.swing.JButton();
        botonañadir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("SDMT - VENTA DE PRODUCTOS ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 21, -1, -1));

        cbnombre.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnombreActionPerformed(evt);
            }
        });
        getContentPane().add(cbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 91, 372, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        contadorproductos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        contadorproductos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        contadorproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contadorproductosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contadorproductosKeyTyped(evt);
            }
        });
        getContentPane().add(contadorproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 132, 62, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 185, 121, 51));

        botonañadir.setText("AÑADIR");
        botonañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonañadirActionPerformed(evt);
            }
        });
        getContentPane().add(botonañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 185, 121, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/papyrus.jpg"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void cbnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnombreActionPerformed
        if(cbnombre.getSelectedIndex() != -1){
           new libAñadirProducto().SetMaxValue();
           botonañadir.setEnabled(true);
        }
        else{
            botonañadir.setEnabled(false);
        }
    }//GEN-LAST:event_cbnombreActionPerformed

    private void botonañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonañadirActionPerformed
        if(new libAñadirProducto().VerificarEspaciosAñadir()){
            JOptionPane.showMessageDialog(null, "PORFAVOR SELECCIONE EL PRODUCTO/CANTIDAD CORRECTO/S", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            new libAñadirProducto().CargarTablaVentas();
            this.setVisible(false);
            new libAñadirProducto().CalcularSubtotal();
            new libVentaProductos().ModificarCantidadEspecifica();
        }
        
    }//GEN-LAST:event_botonañadirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        
    }//GEN-LAST:event_formWindowDeactivated

    private void contadorproductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadorproductosKeyPressed
        
        
    }//GEN-LAST:event_contadorproductosKeyPressed

    private void contadorproductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contadorproductosKeyTyped
        
    }//GEN-LAST:event_contadorproductosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirProducto().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonañadir;
    private javax.swing.JButton botoncancelar;
    public static javax.swing.JComboBox<String> cbnombre;
    public static javax.swing.JSpinner contadorproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
