/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import libraries.formularios.libConsultaRecargas;
import libraries.identidades.ConsultaRecarga;

/**
 *
 * @author Ellet
 */
public class ConsultaRecargas extends javax.swing.JFrame {
    libConsultaRecargas lcr = new libConsultaRecargas();
    /**
     * Creates new form ConsultaRecargas
     */
    public ConsultaRecargas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonimprimir = new javax.swing.JButton();
        txtbusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbconsultarecargas = new javax.swing.JTable();
        cbcategoria = new javax.swing.JComboBox<>();
        botonconsultar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        lbtotalesconsulta = new javax.swing.JLabel();
        lbtotales = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("SDMT  CONSULTA DE RECARGAS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonimprimir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonimprimir.setText("IMPRIMIR");
        botonimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonimprimirActionPerformed(evt);
            }
        });
        getContentPane().add(botonimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 439, 144, 64));

        txtbusqueda.setEnabled(false);
        getContentPane().add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 136, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("CATEGORIA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 91, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE RECARGAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 23, -1, -1));

        tbconsultarecargas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbconsultarecargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO RECARGA", "FECHA", "NUMERO", "MONTO", "EMPLEADO", "PROMOCION", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbconsultarecargas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbconsultarecargas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 768, 156));

        cbcategoria.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FECHA", "NUMERO", "EMPLEADO" }));
        cbcategoria.setSelectedIndex(-1);
        cbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 88, 117, -1));

        botonconsultar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonconsultar.setText("CONSULTAR");
        botonconsultar.setEnabled(false);
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 68, 144, 64));

        botonsalir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonsalir.setText("SALIR");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 439, 144, 64));

        lbtotalesconsulta.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbtotalesconsulta.setText("TOTALES CONSULTA:");
        getContentPane().add(lbtotalesconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 382, -1, -1));

        lbtotales.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbtotales.setText(" ");
        getContentPane().add(lbtotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 382, 81, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_muñequito_invisible.jpg"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoriaActionPerformed
        if(cbcategoria.getSelectedIndex() == 0){
            txtbusqueda.setText("YYYY/MM/DD");
            txtbusqueda.setEnabled(true);
            botonconsultar.setEnabled(true);
        }
        else{
            if(cbcategoria.getSelectedIndex() == 1){
                txtbusqueda.setText("");
                txtbusqueda.setEnabled(true);
                botonconsultar.setEnabled(true);
            }
            else{
                txtbusqueda.setText("");
                txtbusqueda.setEnabled(true);
                botonconsultar.setEnabled(true);
            }
            
        }

    }//GEN-LAST:event_cbcategoriaActionPerformed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        tbconsultarecargas.setModel(LlenarModelo());
        lbtotales.setText(lcr.SumaTotalesConsulta(array()));
        cbcategoria.setSelectedIndex(-1);
        txtbusqueda.setText("");
        txtbusqueda.setEnabled(false);
        botonconsultar.setEnabled(false);
    }//GEN-LAST:event_botonconsultarActionPerformed

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        Limpiar();
        this.setVisible(false);
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botonimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonimprimirActionPerformed
        Imprimir();
        Limpiar();
    }//GEN-LAST:event_botonimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaRecargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaRecargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaRecargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaRecargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaRecargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botonimprimir;
    private javax.swing.JButton botonsalir;
    private javax.swing.JComboBox<String> cbcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbtotales;
    public static javax.swing.JLabel lbtotalesconsulta;
    private javax.swing.JTable tbconsultarecargas;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
    
    public void Limpiar(){
        DefaultTableModel modelo = (DefaultTableModel) tbconsultarecargas.getModel();
        modelo.setRowCount(0);
        tbconsultarecargas.setModel(modelo);
        txtbusqueda.setText("");
        lbtotales.setText(" ");
    }
    
    public void Imprimir(){
        MessageFormat hf = new MessageFormat("Recargas");
        MessageFormat ff = new MessageFormat(lbtotalesconsulta.getText()+ "  " + ConsultaRecargas.lbtotales.getText());
        try{
            tbconsultarecargas.print(JTable.PrintMode.FIT_WIDTH,hf,ff);
        }
        catch(PrinterException exc){
            JOptionPane.showMessageDialog(null,exc.getMessage(),"WARNING!",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public double [] array(){
        double array [] = new double[tbconsultarecargas.getRowCount()];
        int c = 0;
        while(c < array.length){
            array[c] = (Double)tbconsultarecargas.getValueAt(c, 6);
            c++;
        }
        return array;
    }
    
  
    public DefaultTableModel LlenarModelo(){
        List<ConsultaRecarga> recargas = lcr.Busqueda(txtbusqueda.getText(),cbcategoria.getSelectedIndex());
        Object fila [] = new Object[tbconsultarecargas.getColumnCount()];
        DefaultTableModel dtm = (DefaultTableModel)tbconsultarecargas.getModel();
        dtm.setRowCount(0);
        if(!recargas.isEmpty()){
            for(ConsultaRecarga recarga : recargas){
                fila[0] = recarga.getCodigoRecarga();
                fila[1] = recarga.getFecha();
                fila[2] = recarga.getNumero();
                fila[3] = recarga.getMonto();
                fila[4] = recarga.getEmpleado();
                fila[5] = recarga.getPromocion();
                fila[6] = recarga.getTotal();
                dtm.addRow(fila);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"NO SE ENCONTRO REGISTROS","NOT FOUND",JOptionPane.INFORMATION_MESSAGE);
        }
        return dtm;
    }
}
