/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import libraries.formularios.libConsultarVentaProducto;
import libraries.identidades.ConsultaVentaProducto;
/**
 *
 * @author Ellet
 */
public class ConsultaVenta extends javax.swing.JFrame {
    libConsultarVentaProducto lcv = new libConsultarVentaProducto();
    /**
     * Creates new form ConsultaVentas
     */
    public ConsultaVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtbusqueda.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbcategoria = new javax.swing.JComboBox<>();
        botonconsultar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        botonimprimir = new javax.swing.JButton();
        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultaventasproducto = new javax.swing.JTable();
        lbtotales = new javax.swing.JLabel();
        lbtotalesconsulta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("SDMT - CONSULTA DE VENTAS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("CATEGORIA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 91, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE VENTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 23, -1, -1));

        cbcategoria.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FECHA", "PRODUCTO" }));
        cbcategoria.setSelectedIndex(-1);
        cbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 88, 117, -1));

        botonconsultar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonconsultar.setText("CONSULTAR");
        botonconsultar.setEnabled(false);
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 68, 144, 64));

        botonsalir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonsalir.setText("SALIR");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 449, 144, 64));

        botonimprimir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonimprimir.setText("IMPRIMIR");
        botonimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonimprimirActionPerformed(evt);
            }
        });
        getContentPane().add(botonimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 449, 144, 64));
        getContentPane().add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 136, -1));

        tablaconsultaventasproducto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tablaconsultaventasproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO FACTURA", "FECHA", "NOMBRE CLIENTE", "CODIGO PRODUCTO", "NOMBRE PRODUCTO", "PRECIO UNITARIO", "CANTIDAD", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaconsultaventasproducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaconsultaventasproducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 189, 768, 156));

        lbtotales.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbtotales.setText(" ");
        getContentPane().add(lbtotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 380, 81, -1));

        lbtotalesconsulta.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbtotalesconsulta.setText("TOTALES CONSULTA:");
        getContentPane().add(lbtotalesconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_muñequito_invisible.jpg"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        this.setVisible(false);
        Limpiar();
        
    }//GEN-LAST:event_botonsalirActionPerformed

    private void cbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoriaActionPerformed
            if(cbcategoria.getSelectedIndex() == 0){
                txtbusqueda.setText("YYYY/MM/DD");
                txtbusqueda.setEnabled(true);
                botonconsultar.setEnabled(true);
            }
            else{
                txtbusqueda.setText("");
                txtbusqueda.setEnabled(true);
                botonconsultar.setEnabled(true);
            }
            
        
    }//GEN-LAST:event_cbcategoriaActionPerformed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        tablaconsultaventasproducto.setModel(LlenarModelo());
        cbcategoria.setSelectedIndex(-1);
        txtbusqueda.setText("");
        txtbusqueda.setEnabled(false);
        botonconsultar.setEnabled(false);
        lbtotales.setText(lcv.SumaTotalesConsulta(array()));
        
    }//GEN-LAST:event_botonconsultarActionPerformed

    private void botonimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonimprimirActionPerformed
        Imprimir();
        Limpiar();
    }//GEN-LAST:event_botonimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVenta().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botonimprimir;
    private javax.swing.JButton botonsalir;
    private javax.swing.JComboBox<String> cbcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbtotales;
    public static javax.swing.JLabel lbtotalesconsulta;
    private javax.swing.JTable tablaconsultaventasproducto;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
    
    public void Imprimir(){
        MessageFormat hf = new MessageFormat("Ventas");
        MessageFormat ff = new MessageFormat(lbtotalesconsulta.getText()+ "  " + lbtotales.getText());
        try{
            tablaconsultaventasproducto.print(JTable.PrintMode.FIT_WIDTH,hf,ff);
        }
        catch(PrinterException exc){
            JOptionPane.showMessageDialog(null,exc.getMessage(),"WARNING!",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void Limpiar(){
        DefaultTableModel modelo = (DefaultTableModel) tablaconsultaventasproducto.getModel();
        modelo.setRowCount(0);
        tablaconsultaventasproducto.setModel(modelo);
        txtbusqueda.setText("");
        lbtotales.setText(" ");
    }
    
    public double [] array(){
        double array [] = new double[tablaconsultaventasproducto.getRowCount()];
        int c = 0;
        while(c < array.length){
            array[c] = (Double) tablaconsultaventasproducto.getValueAt(c, 7);
            c++;
        }
        return array;
    }
    
        
    public DefaultTableModel LlenarModelo(){
        List<ConsultaVentaProducto> ventas =lcv.Busqueda(txtbusqueda.getText(),cbcategoria.getSelectedIndex());
        Object [] fila = new Object[tablaconsultaventasproducto.getColumnCount()];
        DefaultTableModel dtm = (DefaultTableModel) tablaconsultaventasproducto.getModel();
        dtm.setRowCount(0);
        if(!ventas.isEmpty()){
            for(ConsultaVentaProducto venta : ventas){
                fila[0] = venta.getCodigoFactura();
                fila[1] = venta.getFecha();
                fila[2] = venta.getNombreCliente();
                fila[3] = venta.getCodigoProducto();
                fila[4] = venta.getNombreProducto();
                fila[5] = venta.getPrecioUnitario();
                fila[6] = venta.getCantidad();
                fila[7] = venta.getTotal();
                dtm.addRow(fila);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"NO SE ENCONTRO REGISTROS","NOT FOUND",JOptionPane.INFORMATION_MESSAGE);
        }
        return dtm;
    }


}
