/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;

import Formularios.Principal.Principal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import libraries.formularios.dbEmpleados;
import libraries.formularios.dbPromociones;
import libraries.formularios.libRecargas;
import libraries.formularios.libValidacionesTexto;
import libraries.identidades.Empleado;
import libraries.identidades.Promocion;
import libraries.identidades.VentaRecarga;
/**
 *
 * @author Ellet
 */
public class Recargas extends javax.swing.JFrame {
    dbPromociones dbp = new dbPromociones();
    libRecargas lr = new libRecargas();
    dbEmpleados dbe = new dbEmpleados();
    DefaultListModel dlm = new DefaultListModel();
    /**
     * Creates new form Recargas
     */
    public Recargas() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargarPromociones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonRecarga = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbpromociones = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        botoncancelar = new javax.swing.JButton();
        botonrecargar = new javax.swing.JButton();
        txtnumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setTitle("SDMT - RECARGAS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("NUMERO: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 84, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "PROMOCION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.setOpaque(false);

        cbpromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpromocionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbpromociones, 0, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbpromociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "CANTIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);

        GrupoBotonRecarga.add(rb1);
        rb1.setText("$ 1");
        rb1.setOpaque(false);
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        GrupoBotonRecarga.add(rb3);
        rb3.setText("$ 3");
        rb3.setOpaque(false);

        GrupoBotonRecarga.add(rb6);
        rb6.setText("$ 6");
        rb6.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1)
                    .addComponent(rb3)
                    .addComponent(rb6))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb1)
                .addGap(18, 18, 18)
                .addComponent(rb3)
                .addGap(18, 18, 18)
                .addComponent(rb6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 141, -1, -1));

        botoncancelar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 312, 119, 44));

        botonrecargar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonrecargar.setText("RECARGAR");
        botonrecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrecargarActionPerformed(evt);
            }
        });
        getContentPane().add(botonrecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 312, 119, 44));

        txtnumero.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtnumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumeroFocusLost(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 81, 136, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("RECARGAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/recargas.jpg"))); // NOI18N
        jLabel8.setText(" ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void cbpromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpromocionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpromocionesActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void botonrecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrecargarActionPerformed
        if(ValidarEspaciosRecargar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS","WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            VentaRecarga factura  = Recargar();
            FacturaRecargas fac = new FacturaRecargas();
            fac.setFactura(factura);
            fac.setVisible(true);
            Limpiar();
            
        }
        
    }//GEN-LAST:event_botonrecargarActionPerformed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        new libValidacionesTexto().ValidacionNumerica(evt);
        new libValidacionesTexto().ValidarLongitudNumero(evt, txtnumero.getText().length());
        
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtnumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumeroFocusLost
        
    }//GEN-LAST:event_txtnumeroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup GrupoBotonRecarga;
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonrecargar;
    private javax.swing.JComboBox cbpromociones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
    
    public void Limpiar(){
        cbpromociones.setSelectedIndex(-1);
        GrupoBotonRecarga.clearSelection();
        txtnumero.setText("");
    }
    
    public boolean ValidarEspaciosRecargar(){
        boolean espacios = false;
        if(txtnumero.getText().replaceAll("\\s", "").equals("")){
            espacios = true;
        }
        if(cbpromociones.getSelectedIndex() == -1){
            espacios = true;
        }
        if(!(rb1.isSelected() || rb3.isSelected() || rb6.isSelected())){
            espacios = true;
        }
        if(txtnumero.getText().length() <= 9){
            espacios = true;
        }
        return espacios;
    }
    
    public void CargarPromociones(){
        List<Promocion> promociones = dbp.CargarPromociones();
        cbpromociones.removeAllItems();
        dlm.removeAllElements();
        for(Promocion promocion : promociones){
            cbpromociones.addItem(promocion.getNombre_promocion());
            dlm.addElement(promocion);
        }
        cbpromociones.setSelectedIndex(-1);
    }
    
    public VentaRecarga Recargar(){
        Promocion promocion = (Promocion) dlm.getElementAt(cbpromociones.getSelectedIndex());
        Empleado empleado = dbe.ConsultarRegistros(Principal.codigoEmpleado);
        String parametro = cbpromociones.getSelectedItem().toString();
        double monto = lr.Monto(TextoRb());
        VentaRecarga recarga = new VentaRecarga(lr.ObtenerFecha(),"CONSUMIDOR FINAL",txtnumero.getText(),
                                                (int)monto,empleado,promocion,
                                                lr.ConvertirFormatear(lr.AumentoPromocion(monto,parametro)).doubleValue());
        lr.RealizarRecarga(recarga);
        return recarga;
    }
    
    public String TextoRb(){
        if(rb1.isSelected()){
            return rb1.getText();
        }
        else{
            if(rb3.isSelected()){
                return rb3.getText();
            }
            else{
                return rb6.getText();
            }
        }
    }
    
    
            
            
}
