/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Ventas;
import Formularios.Principal.Principal;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JTable;


import javax.swing.table.DefaultTableModel;
import libraries.formularios.libAñadirProducto;
import libraries.formularios.libValidacionesTexto;

import libraries.formularios.libVentaProductos;
/**
 *
 * @author Ellet
 */
public class VentaProducto extends javax.swing.JFrame implements Printable {
    public static JTable simulacion = new JTable();
    
    
    public VentaProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) VentaProducto.tbventas.getModel();
        modelo.setRowCount(0);
        new libVentaProductos().InicializarPopUp();
        new libAñadirProducto().AñadirProductoTabla();
        new libVentaProductos().CargarDatosEmpleado();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopEliminar = new javax.swing.JPopupMenu();
        botoncancelar = new javax.swing.JButton();
        botonfacturar = new javax.swing.JButton();
        botonañadirproducto = new javax.swing.JButton();
        plfactura = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbcedulaempleado = new javax.swing.JLabel();
        lbnombreempleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbapellidoempleado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbventas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombrecliente = new javax.swing.JTextField();
        txtcedulacliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        txtiva = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        PopEliminar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PopEliminar.setToolTipText("ELIMINAR");
        PopEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopEliminarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopEliminarMousePressed(evt);
            }
        });
        PopEliminar.getAccessibleContext().setAccessibleName("ELIMINAR");

        setTitle("SDMT - VENTA DE PRODUCTOS");
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botoncancelar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 573, 187, 55));

        botonfacturar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonfacturar.setText("FACTURAR");
        botonfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfacturarActionPerformed(evt);
            }
        });
        getContentPane().add(botonfacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 573, 190, 55));

        botonañadirproducto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonañadirproducto.setText("AÑADIR PRODUCTO");
        botonañadirproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonañadirproductoActionPerformed(evt);
            }
        });
        getContentPane().add(botonañadirproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 575, 190, 50));

        plfactura.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "DATOS DE CAJA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbcedulaempleado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbcedulaempleado.setText("  ");
        jPanel2.add(lbcedulaempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 100, 410, -1));

        lbnombreempleado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbnombreempleado.setText(" ");
        jPanel2.add(lbnombreempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 30, 410, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRES EMPLEADO:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("APELLIDOS EMPLEADO:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 65, -1, -1));

        lbapellidoempleado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbapellidoempleado.setText("  ");
        jPanel2.add(lbapellidoempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 65, 410, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("CEDULA EMPLEADO:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel3.setText("SDMT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        lblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_smdt.jpg"))); // NOI18N
        lblogo.setText(" ");
        jPanel2.add(lblogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 150, 60));

        tbventas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "DESCRIPCION", "PRECIO UNITARIO", "CANTIDAD", "PRECIO POR PRODUCTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbventas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbventas);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE CLIENTE:");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("C.I./RUC:");

        txtnombrecliente.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtnombrecliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreclienteKeyTyped(evt);
            }
        });

        txtcedulacliente.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtcedulacliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaclienteFocusLost(evt);
            }
        });
        txtcedulacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaclienteActionPerformed(evt);
            }
        });
        txtcedulacliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaclienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(txtnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(61, 61, 61)
                .addComponent(txtcedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtcedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("SUBTOTAL:");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("IVA 14%:");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("TOTAL:");

        txtsubtotal.setEditable(false);
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        txtiva.setEditable(false);
        txtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtivaActionPerformed(evt);
            }
        });

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plfacturaLayout = new javax.swing.GroupLayout(plfactura);
        plfactura.setLayout(plfacturaLayout);
        plfacturaLayout.setHorizontalGroup(
            plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plfacturaLayout.createSequentialGroup()
                .addGroup(plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plfacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plfacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plfacturaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plfacturaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plfacturaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)
                                .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plfacturaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(62, 62, 62)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(plfacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plfacturaLayout.setVerticalGroup(
            plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plfacturaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(plfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(plfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 960, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pin pon en un muñeco.jpg"))); // NOI18N
        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void botonañadirproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonañadirproductoActionPerformed
        new AñadirProducto().setVisible(true);
        
    }//GEN-LAST:event_botonañadirproductoActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtivaActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void PopEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopEliminarMouseClicked
        
    }//GEN-LAST:event_PopEliminarMouseClicked

    private void PopEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopEliminarMousePressed
        
    }//GEN-LAST:event_PopEliminarMousePressed

    private void botonfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfacturarActionPerformed
        if(new libVentaProductos().ValidarEspaciosFacturar()){
            JOptionPane.showMessageDialog(null, "PORFAVOR LLENAR TODOS LOS DATOS ANTES DE FACTURAR","WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            new libVentaProductos().GuardarDatosFactura();
            new libVentaProductos().GuardarVentasProducto();
            new libVentaProductos().ModificarCantidadMenos();
            new libVentaProductos().EjecutarActualizacionInventario();
            JOptionPane.showMessageDialog(null,"VENTA EXITOSA", "SUCESS", JOptionPane.INFORMATION_MESSAGE);
            ImprimirFactura();
        }
        
        
    }//GEN-LAST:event_botonfacturarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void txtcedulaclienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaclienteFocusLost
        
    }//GEN-LAST:event_txtcedulaclienteFocusLost

    private void txtcedulaclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaclienteKeyTyped
        new libValidacionesTexto().ValidacionNumerica(evt);
        new libValidacionesTexto().ValidarLongitudCedula(evt, txtcedulacliente.getText().length());
        
    }//GEN-LAST:event_txtcedulaclienteKeyTyped

    private void txtcedulaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaclienteActionPerformed
        
    }//GEN-LAST:event_txtcedulaclienteActionPerformed

    private void txtnombreclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreclienteKeyTyped
        new libValidacionesTexto().ValidacionesCaracteresEspeciales(evt);
    }//GEN-LAST:event_txtnombreclienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaProducto().setVisible(true);
            }
        });
    }
    
    public void Limpiar(){
        DefaultTableModel modelo = (DefaultTableModel) tbventas.getModel();
        modelo.setRowCount(0);
        tbventas.setModel(modelo);
        txtnombrecliente.setText("");
        txtcedulacliente.setText("");
        txtsubtotal.setText("");
        txtiva.setText("");
        txttotal.setText("");
        botonañadirproducto.setEnabled(false);
        botonfacturar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPopupMenu PopEliminar;
    private javax.swing.JButton botonañadirproducto;
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonfacturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbapellidoempleado;
    public static javax.swing.JLabel lbcedulaempleado;
    private javax.swing.JLabel lblogo;
    public static javax.swing.JLabel lbnombreempleado;
    public static javax.swing.JPanel plfactura;
    public static javax.swing.JTable tbventas;
    public static javax.swing.JTextField txtcedulacliente;
    public static javax.swing.JTextField txtiva;
    public static javax.swing.JTextField txtnombrecliente;
    public static javax.swing.JTextField txtsubtotal;
    public static javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    public void ImprimirFactura(){
        PrinterJob pj = PrinterJob.getPrinterJob();
        PageFormat pf = new PageFormat();
        try{
            pf.setOrientation(PageFormat.LANDSCAPE);
            pj.setPrintable((Printable) this,pf);
            if(pj.printDialog()){
            pj.print();
            Limpiar();
            }
        }
        catch(PrinterException exc){
            JOptionPane.showMessageDialog(null, exc.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public int print(Graphics graf, PageFormat pf, int index) throws PrinterException {
        if(index > 0){
            return Printable.NO_SUCH_PAGE;
        }
        else{
            Graphics2D g2d = (Graphics2D) graf;
            g2d.translate(pf.getImageableX() + 30, pf.getImageableY() + 30);
            g2d.scale(0.50, 0.50);
            
            VentaProducto.plfactura.printAll(graf);
            return Printable.PAGE_EXISTS;
        }
    }
}
